/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
    interface LatvianFlag {
        /**
         * @default ''
         */
        class: string;
        /**
         * @default ''
         */
        class2: string;
    }
}
declare global {
    interface HTMLLatvianFlagElement extends Components.LatvianFlag, HTMLStencilElement {}
    var HTMLLatvianFlagElement: {
        prototype: HTMLLatvianFlagElement;
        new (): HTMLLatvianFlagElement;
    };
    interface HTMLElementTagNameMap {
        'latvian-flag': HTMLLatvianFlagElement;
    }
}
declare namespace LocalJSX {
    interface LatvianFlag {
        /**
         * @default ''
         */
        class?: string;
        /**
         * @default ''
         */
        class2?: string;
    }
    interface IntrinsicElements {
        'latvian-flag': LatvianFlag;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'latvian-flag': LocalJSX.LatvianFlag & JSXBase.HTMLAttributes<HTMLLatvianFlagElement>;
        }
    }
}
