/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LatvianFlag {
        /**
          * Aspect ratio (width divided by height) used when only the width is provided.
          * @default 2
         */
        "aspectRatio": string | number;
        /**
          * Border color used with `border-width`.
          * @default 'transparent'
         */
        "borderColor": string;
        /**
          * Border radius applied to the flag container.
          * @default '0'
         */
        "borderRadius": string | number;
        /**
          * Border width applied around the flag.
          * @default 0
         */
        "borderWidth": string | number;
        /**
          * Percentage (0-1) of the flag's height dedicated to the center stripe.
          * @default 0.2
         */
        "centerStripeRatio": string | number;
        /**
          * Optional explicit height. Falls back to a compact default when omitted.
         */
        "height"?: string | number;
        /**
          * Background color for the center stripe.
          * @default '#ffffff'
         */
        "innerColor": string;
        /**
          * Controls whether the maroon bands run vertically (default) or horizontally.
          * @default 'vertical'
         */
        "orientation": 'vertical' | 'horizontal';
        /**
          * Background color for the maroon stripes.
          * @default '#960018'
         */
        "outerColor": string;
        /**
          * Explicit width for the rendered flag. Numbers are treated as pixels.
         */
        "width"?: string | number;
    }
    interface ValksorLogo {
        /**
          * Optional height override; falls back to `size` when not provided.
         */
        "height"?: string;
        /**
          * Controls both width and height. Accepts any valid CSS length.
          * @default '120px'
         */
        "size": string;
        /**
          * Optional width override; falls back to `size` when not provided.
         */
        "width"?: string;
    }
}
declare global {
    interface HTMLLatvianFlagElement extends Components.LatvianFlag, HTMLStencilElement {
    }
    var HTMLLatvianFlagElement: {
        prototype: HTMLLatvianFlagElement;
        new (): HTMLLatvianFlagElement;
    };
    interface HTMLValksorLogoElement extends Components.ValksorLogo, HTMLStencilElement {
    }
    var HTMLValksorLogoElement: {
        prototype: HTMLValksorLogoElement;
        new (): HTMLValksorLogoElement;
    };
    interface HTMLElementTagNameMap {
        "latvian-flag": HTMLLatvianFlagElement;
        "valksor-logo": HTMLValksorLogoElement;
    }
}
declare namespace LocalJSX {
    interface LatvianFlag {
        /**
          * Aspect ratio (width divided by height) used when only the width is provided.
          * @default 2
         */
        "aspectRatio"?: string | number;
        /**
          * Border color used with `border-width`.
          * @default 'transparent'
         */
        "borderColor"?: string;
        /**
          * Border radius applied to the flag container.
          * @default '0'
         */
        "borderRadius"?: string | number;
        /**
          * Border width applied around the flag.
          * @default 0
         */
        "borderWidth"?: string | number;
        /**
          * Percentage (0-1) of the flag's height dedicated to the center stripe.
          * @default 0.2
         */
        "centerStripeRatio"?: string | number;
        /**
          * Optional explicit height. Falls back to a compact default when omitted.
         */
        "height"?: string | number;
        /**
          * Background color for the center stripe.
          * @default '#ffffff'
         */
        "innerColor"?: string;
        /**
          * Controls whether the maroon bands run vertically (default) or horizontally.
          * @default 'vertical'
         */
        "orientation"?: 'vertical' | 'horizontal';
        /**
          * Background color for the maroon stripes.
          * @default '#960018'
         */
        "outerColor"?: string;
        /**
          * Explicit width for the rendered flag. Numbers are treated as pixels.
         */
        "width"?: string | number;
    }
    interface ValksorLogo {
        /**
          * Optional height override; falls back to `size` when not provided.
         */
        "height"?: string;
        /**
          * Controls both width and height. Accepts any valid CSS length.
          * @default '120px'
         */
        "size"?: string;
        /**
          * Optional width override; falls back to `size` when not provided.
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "latvian-flag": LatvianFlag;
        "valksor-logo": ValksorLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "latvian-flag": LocalJSX.LatvianFlag & JSXBase.HTMLAttributes<HTMLLatvianFlagElement>;
            "valksor-logo": LocalJSX.ValksorLogo & JSXBase.HTMLAttributes<HTMLValksorLogoElement>;
        }
    }
}
